package:
    name: ocr-from-clipboard
    version: 1.0.0

source:
    git_rev: v1.0.0
    git_url: https://github.com/Alessio-Olivieri/simple-ocr 
    git_clone_depth: 0

requirements:
    build:
        - python >=3.8
        - setuptools >=40.8.0
        - pytesseract
        - pillow

    run:
        - python >=3.8
        - pytesseract
        - pillow

test:
    imports:
        - simple-ocr 

about:
    home: https://github.com/Alessio-Olivieri/simple-ocr 